name: Android Build AppCenter Prod

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: ./.github/actions/gradle_docker
      with:
        gradle-cmd: assembleProdRelease -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        appName: ${{secrets.APPCENTER_ORGANIZATION}}/${{secrets.APPCENTER_APP}}
        token: ${{secrets.APPCENTER_API_TOKEN}}
        group: Internal
        file: app/build/outputs/apk/prod/release/app-prod-release.apk
