name: Android Build AppCenter Abn

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: ./.github/actions/gradle_docker
      with:
        gradle-cmd: assembleAbnRelease -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        appName: ${{secrets.APPCENTER_ORGANIZATION}}/${{secrets.APPCENTER_APP_ABN}}
        token: ${{secrets.APPCENTER_API_TOKEN}}
        group: public
        file: app/build/outputs/apk/abn/release/app-abn-release.apk
